### ISSUE TITLE
There is no report whatsoever but exit with code.

### ISSUE THREAD

**Issue by dwisiswant0** [Bearer/curio-action#56]
![image](https://github.com/Bearer/bearer-action/assets/25837540/3f753d98-e2da-492e-8b4e-179fcfe3696a)

**Comment by elsapet** [comment]
Thanks for raising @dwisiswant0 
From line 15 in the output provided, it looks like the `exit-code` flag is being set to `1` (see https://github.com/Bearer/bearer-action?tab=readme-ov-file#exit-code). This would cause Bearer to always return exit code `1`. Do you see the same behaviour if you remove this flag?

**Comment by dwisiswant0** [comment]
> This would cause Bearer to **always** return exit code `1`

So are you saying that if the `exit-code` flag is set, it's gonna exit with that code no matter what? Even if there ain't no security report/findings?

**Comment by elsapet** [comment]
> So are you saying that if the exit-code flag is set, it's gonna exit with that code no matter what?

Yes, this is correct 👍 

The default behaviour (when the flag is not set) is to return exit code `1` when there are findings, and exit code `0` (success) when there are no findings. 

For interest, the typical use-case for the `exit-code` flag is for people who want to run Bearer as part of their CI but do not want Bearer to fail their CI pipeline (for whatever reason). In this case they set the flag to `0` (always passing).

**Comment by dwisiswant0** [comment]
Alright, I understand. At first, I believed that the default behavior of the action was always to pass (exit with a `0` code) even if it found findings. So, I set a value for the `exit-code` input to instruct the engine to exit with a specific code if it detected any findings.

In my view, this design is somewhat confusing for DX in CI environments. Why not use a different input name, such as `fail-ci-if-errors` and/or `always-pass`/`pass-errors`, with a simple boolean value? This would make things much simpler and clearer.

Anyway, thanks for clearing that up, @elsapet. I'll go ahead and close this now.
